package edu.chl.codenameg.model;

public enum Action {
	START_GAME,
	PLAYER_1_MOVE_LEFT,
	PLAYER_1_MOVE_RIGHT,
	PLAYER_1_JUMP,
	PLAYER_2_MOVE_RIGHT,
	PLAYER_2_MOVE_LEFT,
	PLAYER_2_JUMP,
	
	NO_ACTION
}
